### PR TITLE
Prevent patient DOB from being edited by sending in a copy of the DOB to compute the age from birth date

### PR DESCRIPTION
**Pull request by zplata**
Currently, in the SMART Cardiac Risk App, the DOB on the patient banner displayed the date of the patient's last birthday. The function `computeAgeFromBirthDate` was editing the date passed in the parameter (which was the actual patient's DOB property). 

One solution is to send in a copy of the DOB property to this function, thus not affecting the patient's actual DOB property when trying to calculate the age. Then the age will appropriately match the patient's DOB. Screenshots below.

1_before
2_after

@kpshek 
@mjhenkes 
@kolkheang
@koushic88
@shriniketsarkar

### CODE REVIEW

**Comment by shriniketsarkar** [comment]
+1 Dumb coding mistake on my part 😔 ....Really sad that our testing also didn't catch it. Zach we need to notify Stefan to add a test case for this in his testing.
Thanks for noticing and fixing this.

**Comment by kolkheang** [comment]
+1

**Comment by mjhenkes** [comment]
+1

**Comment by kpshek** [comment]
👍 

I know the tests in the ascvd branch are a complete mess right now (I've been ignoring them during this transition from reynolds to ascvd) so I'm overlooking the lack of a test update/addition with this change.

As an aside, are we also fixing this in our old reynolds version? I'm fine if we don't fix this there given that we know that the demographics banner is not displayed based upon our current production EHR use.

**Comment by zplata** [comment]
@kpshek I'll make sure to update the tests for this function when we start the process of cleaning up the test suite. As for the old RRS version, we will be fixing this defect in there as well.

**Pull request merged**
